export type Level = {
  level: number;
  title: string;
  challengeType: string;
  example: string;
  isCompleted?: boolean;
};

export type Tier = {
  tier: number;
  title: string;
  focus: string;
  goal: string;
  levels: Level[];
};

export type Branch = 'CSE' | 'CSM' | 'CSD' | 'CSC' | 'IT' | 'ECE' | 'EEE' | 'MECH' | 'CIVIL' | 'General';

export type SkillTrack = {
  slug: string;
  title: string;
  description: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  category: 'Technical' | 'Soft Skill';
  branch: Branch;
  imageId: string;
  journey: Tier[];
};

export const branches: { id: Branch; name: string; description: string }[] = [
  { id: 'General', name: 'General', description: 'Skills for all branches' },
  { id: 'CSE', name: 'Computer Science', description: 'Core CS skills' },
  { id: 'CSM', name: 'CS (AI & ML)', description: 'AI/ML focused skills' },
  { id: 'CSD', name: 'CS (Data Science)', description: 'Data Science skills' },
  { id: 'CSC', name: 'CS (Cyber Security)', description: 'Cyber Security skills' },
  { id: 'IT', name: 'Information Technology', description: 'IT focused skills' },
  { id: 'ECE', name: 'Electronics & Communication', description: 'ECE skills' },
  { id: 'EEE', name: 'Electrical Engineering', description: 'EEE skills' },
  { id: 'MECH', name: 'Mechanical Engineering', description: 'Mechanical skills' },
  { id: 'CIVIL', name: 'Civil Engineering', description: 'Civil engineering skills' },
];

export const skillTracks: Omit<SkillTrack, 'journey'>[] = [
  // CSE Branch Skills
  {
    slug: 'python-for-data-science',
    title: 'Python for Data Science',
    description: 'Master Python programming for data analysis and machine learning.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-python',
  },
  {
    slug: 'data-structures-algorithms',
    title: 'Data Structures & Algorithms',
    description: 'Master fundamental DSA concepts for competitive programming and interviews.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-dsa',
  },
  {
    slug: 'web-development-fundamentals',
    title: 'Web Development Fundamentals',
    description: 'Build modern web applications with HTML, CSS, JavaScript and React.',
    level: 'Beginner',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-web',
  },
  {
    slug: 'database-management',
    title: 'Database Management',
    description: 'Learn SQL, database design, and management systems.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-database',
  },
  // CSM (AI/ML) Branch Skills
  {
    slug: 'machine-learning-basics',
    title: 'Machine Learning Basics',
    description: 'Introduction to ML algorithms, model training, and evaluation.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSM',
    imageId: 'skill-ml',
  },
  {
    slug: 'deep-learning-neural-networks',
    title: 'Deep Learning & Neural Networks',
    description: 'Build and train neural networks for complex AI tasks.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSM',
    imageId: 'skill-dl',
  },
  {
    slug: 'natural-language-processing',
    title: 'Natural Language Processing',
    description: 'Process and analyze human language with AI techniques.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSM',
    imageId: 'skill-nlp',
  },
  // CSD (Data Science) Branch Skills
  {
    slug: 'data-visualization',
    title: 'Data Visualization',
    description: 'Create compelling visualizations with Python and BI tools.',
    level: 'Beginner',
    category: 'Technical',
    branch: 'CSD',
    imageId: 'skill-viz',
  },
  {
    slug: 'statistical-analysis',
    title: 'Statistical Analysis',
    description: 'Apply statistical methods for data-driven decisions.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSD',
    imageId: 'skill-stats',
  },
  {
    slug: 'big-data-analytics',
    title: 'Big Data Analytics',
    description: 'Process large-scale data with Hadoop, Spark, and cloud tools.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSD',
    imageId: 'skill-bigdata',
  },
  // CSC (Cyber Security) Branch Skills
  {
    slug: 'network-security',
    title: 'Network Security',
    description: 'Protect networks from cyber threats and vulnerabilities.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSC',
    imageId: 'skill-network-sec',
  },
  {
    slug: 'ethical-hacking',
    title: 'Ethical Hacking',
    description: 'Learn penetration testing and security assessment techniques.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSC',
    imageId: 'skill-hacking',
  },
  {
    slug: 'cryptography',
    title: 'Cryptography',
    description: 'Understand encryption algorithms and secure communication.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSC',
    imageId: 'skill-crypto',
  },
  // ECE Branch Skills
  {
    slug: 'embedded-systems',
    title: 'Embedded Systems',
    description: 'Design and program embedded systems and microcontrollers.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'ECE',
    imageId: 'skill-embedded',
  },
  {
    slug: 'vlsi-design',
    title: 'VLSI Design',
    description: 'Learn chip design fundamentals and HDL programming.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'ECE',
    imageId: 'skill-vlsi',
  },
  {
    slug: 'iot-development',
    title: 'IoT Development',
    description: 'Build Internet of Things applications and smart devices.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'ECE',
    imageId: 'skill-iot',
  },
  // General Skills (All Branches)
  {
    slug: 'public-speaking-mastery',
    title: 'Public Speaking Mastery',
    description: 'Learn to deliver compelling presentations with confidence.',
    level: 'Beginner',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-public-speaking',
  },
  {
    slug: 'ui-ux-design-fundamentals',
    title: 'UI/UX Design Fundamentals',
    description: 'Understand the principles of creating user-friendly digital products.',
    level: 'Beginner',
    category: 'Technical',
    branch: 'General',
    imageId: 'skill-ui-ux',
  },
  {
    slug: 'agile-project-management',
    title: 'Agile Project Management',
    description: 'Lead projects effectively with agile methodologies.',
    level: 'Advanced',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-project-management',
  },
  {
    slug: 'technical-writing',
    title: 'Technical Writing',
    description: 'Write clear documentation, reports, and technical content.',
    level: 'Beginner',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-writing',
  },
  {
    slug: 'problem-solving',
    title: 'Problem Solving & Critical Thinking',
    description: 'Develop analytical and problem-solving skills for any domain.',
    level: 'Beginner',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-problem-solving',
  },
  {
    slug: 'interview-preparation',
    title: 'Interview Preparation',
    description: 'Prepare for technical and HR interviews with confidence.',
    level: 'Beginner',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-interview',
  },
];

// Full skill journeys data
export const skillsData: Record<string, SkillTrack> = {
  'python-for-data-science': {
    slug: 'python-for-data-science',
    title: 'Python for Data Science',
    description: 'Master Python programming for data analysis and machine learning.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-python',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Syntax, data types, operators, loops, conditionals.',
        goal: 'Comfort with basics.',
        levels: [
          { level: 1, title: 'Variables & Data Types', challengeType: 'Quiz', example: 'Declare an integer and a string variable.' },
          { level: 2, title: 'Basic Operators', challengeType: 'Quiz', example: 'Calculate the sum of two numbers.' },
          { level: 3, title: 'Conditional Statements', challengeType: 'Simple Exercise', example: 'Write an if-else statement to check if a number is positive.' },
          { level: 4, title: 'For Loops', challengeType: 'Simple Exercise', example: 'Write a loop to print even numbers up to 20.' },
          { level: 5, title: 'While Loops', challengeType: 'Simple Exercise', example: 'Write a loop that runs as long as a variable is less than 10.' },
          { level: 6, title: 'Debugging Snippets I', challengeType: 'Debugging', example: 'Find and fix the error in a simple Python script.' },
          { level: 7, title: 'Lists', challengeType: 'Simple Exercise', example: 'Create a list of fruits and print the second fruit.' },
          { level: 8, title: 'List Methods', challengeType: 'Quiz', example: 'How do you add an item to the end of a list?' },
          { level: 9, title: 'Introduction to Strings', challengeType: 'Simple Exercise', example: 'Concatenate two strings.' },
          { level: 10, title: 'Capstone: Tier 1', challengeType: 'Simple Exercise', example: 'Combine loops and conditionals to print numbers with a condition.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Functions, data structures, OOP basics, file handling.',
        goal: 'Apply coding to solve real tasks.',
        levels: [
          { level: 11, title: 'Defining Functions', challengeType: 'Coding Challenge', example: 'Write a function that takes two numbers and returns their product.' },
          { level: 12, title: 'Function Arguments', challengeType: 'Coding Challenge', example: 'Create a function with default argument values.' },
          { level: 13, title: 'Dictionaries', challengeType: 'Coding Challenge', example: 'Create a dictionary of students and marks, then print the topper name.' },
          { level: 14, title: 'Tuples and Sets', challengeType: 'Quiz', example: 'What is the main difference between a list and a tuple?' },
          { level: 15, title: 'File Handling: Read', challengeType: 'Short Task', example: 'Read a text file and print its content.' },
          { level: 16, title: 'File Handling: Write', challengeType: 'Short Task', example: 'Write a list of strings to a new text file.' },
          { level: 17, title: 'Intro to OOP: Classes', challengeType: 'Coding Challenge', example: 'Create a simple `Dog` class with a `bark` method.' },
          { level: 18, title: 'Intro to OOP: Objects', challengeType: 'Coding Challenge', example: 'Instantiate an object from your `Dog` class.' },
          { level: 19, title: 'Bug Fixing I', challengeType: 'Bug Fixing', example: 'Fix a bug in a function that is not returning the correct value.' },
          { level: 20, title: 'Capstone: Tier 2', challengeType: 'Short Task', example: 'Write a program that reads a CSV file and calculates a column average.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Libraries, APIs, problem-solving, mini-projects.',
        goal: 'Be job-ready in that skill.',
        levels: [
          { level: 21, title: 'NumPy Basics', challengeType: 'Real-world Task', example: 'Create a NumPy array and perform a vectorized operation.' },
          { level: 22, title: 'Pandas DataFrames', challengeType: 'Real-world Task', example: 'Load a CSV into a pandas DataFrame and display the first 5 rows.' },
          { level: 23, title: 'Data Cleaning with Pandas', challengeType: 'Real-world Task', example: 'Handle missing values in a DataFrame.' },
          { level: 24, title: 'Data Visualization with Matplotlib', challengeType: 'Real-world Task', example: 'Create a simple line plot from a list of numbers.' },
          { level: 25, title: 'Introduction to APIs', challengeType: 'API Usage', example: 'Make a GET request to a public API and print the response.' },
          { level: 26, title: 'Working with JSON', challengeType: 'API Usage', example: 'Parse a JSON response from an API.' },
          { level: 27, title: 'Mini-Project: Data Analysis', challengeType: 'Full Program', example: 'Analyze a small dataset and present findings with plots.' },
          { level: 28, title: 'Advanced Problem-Solving', challengeType: 'Full Program', example: 'Solve a complex algorithmic challenge.' },
          { level: 29, title: 'Mini-Project: API App', challengeType: 'Full Program', example: 'Build a weather app that fetches live data using an API.' },
          { level: 30, title: 'Final Capstone Project', challengeType: 'Real-world Project', example: 'Build a complete data analysis project from scratch.' },
        ],
      },
    ],
  },
  'data-structures-algorithms': {
    slug: 'data-structures-algorithms',
    title: 'Data Structures & Algorithms',
    description: 'Master fundamental DSA concepts for competitive programming and interviews.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-dsa',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Arrays, strings, basic complexity analysis.',
        goal: 'Understand basic data structures.',
        levels: [
          { level: 1, title: 'Time Complexity Basics', challengeType: 'Quiz', example: 'What is the time complexity of a single for loop?' },
          { level: 2, title: 'Space Complexity', challengeType: 'Quiz', example: 'What is space complexity and why does it matter?' },
          { level: 3, title: 'Arrays: Traversal', challengeType: 'Coding Challenge', example: 'Write code to find the maximum element in an array.' },
          { level: 4, title: 'Arrays: Two Pointer', challengeType: 'Coding Challenge', example: 'Reverse an array using two pointers.' },
          { level: 5, title: 'Strings: Basics', challengeType: 'Coding Challenge', example: 'Check if a string is a palindrome.' },
          { level: 6, title: 'Strings: Pattern Matching', challengeType: 'Coding Challenge', example: 'Count occurrences of a substring in a string.' },
          { level: 7, title: 'Searching: Linear', challengeType: 'Coding Challenge', example: 'Implement linear search algorithm.' },
          { level: 8, title: 'Searching: Binary', challengeType: 'Coding Challenge', example: 'Implement binary search on a sorted array.' },
          { level: 9, title: 'Sorting: Bubble Sort', challengeType: 'Coding Challenge', example: 'Implement bubble sort algorithm.' },
          { level: 10, title: 'Capstone: Tier 1', challengeType: 'Coding Challenge', example: 'Solve 3 array problems in 30 minutes.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Linked lists, stacks, queues, recursion.',
        goal: 'Apply DSA to solve medium problems.',
        levels: [
          { level: 11, title: 'Linked Lists: Basics', challengeType: 'Coding Challenge', example: 'Create a singly linked list and traverse it.' },
          { level: 12, title: 'Linked Lists: Operations', challengeType: 'Coding Challenge', example: 'Insert and delete nodes from a linked list.' },
          { level: 13, title: 'Stacks: Implementation', challengeType: 'Coding Challenge', example: 'Implement a stack using an array.' },
          { level: 14, title: 'Stacks: Applications', challengeType: 'Coding Challenge', example: 'Check for balanced parentheses using a stack.' },
          { level: 15, title: 'Queues: Implementation', challengeType: 'Coding Challenge', example: 'Implement a queue using an array.' },
          { level: 16, title: 'Recursion: Basics', challengeType: 'Coding Challenge', example: 'Write a recursive function to calculate factorial.' },
          { level: 17, title: 'Recursion: Problems', challengeType: 'Coding Challenge', example: 'Solve the Fibonacci sequence using recursion.' },
          { level: 18, title: 'Sorting: Merge Sort', challengeType: 'Coding Challenge', example: 'Implement merge sort algorithm.' },
          { level: 19, title: 'Sorting: Quick Sort', challengeType: 'Coding Challenge', example: 'Implement quick sort algorithm.' },
          { level: 20, title: 'Capstone: Tier 2', challengeType: 'Coding Challenge', example: 'Solve a linked list reversal problem.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Trees, graphs, dynamic programming.',
        goal: 'Be interview-ready with DSA.',
        levels: [
          { level: 21, title: 'Trees: Binary Tree', challengeType: 'Coding Challenge', example: 'Implement a binary tree with traversal methods.' },
          { level: 22, title: 'Trees: BST', challengeType: 'Coding Challenge', example: 'Implement a binary search tree with insert and search.' },
          { level: 23, title: 'Graphs: Representation', challengeType: 'Coding Challenge', example: 'Represent a graph using adjacency list.' },
          { level: 24, title: 'Graphs: BFS', challengeType: 'Coding Challenge', example: 'Implement breadth-first search.' },
          { level: 25, title: 'Graphs: DFS', challengeType: 'Coding Challenge', example: 'Implement depth-first search.' },
          { level: 26, title: 'Dynamic Programming: Intro', challengeType: 'Coding Challenge', example: 'Solve the climbing stairs problem.' },
          { level: 27, title: 'DP: Classic Problems', challengeType: 'Coding Challenge', example: 'Solve the longest common subsequence problem.' },
          { level: 28, title: 'Hash Tables', challengeType: 'Coding Challenge', example: 'Implement a simple hash table.' },
          { level: 29, title: 'Greedy Algorithms', challengeType: 'Coding Challenge', example: 'Solve the activity selection problem.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Coding Challenge', example: 'Solve 5 mixed DSA problems in 60 minutes.' },
        ],
      },
    ],
  },
  'web-development-fundamentals': {
    slug: 'web-development-fundamentals',
    title: 'Web Development Fundamentals',
    description: 'Build modern web applications with HTML, CSS, JavaScript and React.',
    level: 'Beginner',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-web',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'HTML, CSS basics, page structure.',
        goal: 'Build static web pages.',
        levels: [
          { level: 1, title: 'HTML Structure', challengeType: 'Quiz', example: 'What are the basic HTML tags for a web page?' },
          { level: 2, title: 'HTML Elements', challengeType: 'Simple Exercise', example: 'Create a page with headings, paragraphs, and links.' },
          { level: 3, title: 'HTML Forms', challengeType: 'Simple Exercise', example: 'Build a contact form with input fields.' },
          { level: 4, title: 'CSS Basics', challengeType: 'Simple Exercise', example: 'Style a heading with colors and fonts.' },
          { level: 5, title: 'CSS Box Model', challengeType: 'Quiz', example: 'Explain the CSS box model components.' },
          { level: 6, title: 'CSS Flexbox', challengeType: 'Simple Exercise', example: 'Create a navbar using flexbox.' },
          { level: 7, title: 'CSS Grid', challengeType: 'Simple Exercise', example: 'Build a photo gallery layout using grid.' },
          { level: 8, title: 'Responsive Design', challengeType: 'Simple Exercise', example: 'Make a page responsive using media queries.' },
          { level: 9, title: 'CSS Animations', challengeType: 'Simple Exercise', example: 'Add hover animations to buttons.' },
          { level: 10, title: 'Capstone: Landing Page', challengeType: 'Project', example: 'Build a complete landing page.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'JavaScript fundamentals and DOM manipulation.',
        goal: 'Add interactivity to web pages.',
        levels: [
          { level: 11, title: 'JavaScript Basics', challengeType: 'Quiz', example: 'What are variables, data types in JS?' },
          { level: 12, title: 'Functions & Events', challengeType: 'Coding Challenge', example: 'Create a click event handler.' },
          { level: 13, title: 'DOM Selection', challengeType: 'Coding Challenge', example: 'Select and modify elements using JavaScript.' },
          { level: 14, title: 'DOM Manipulation', challengeType: 'Coding Challenge', example: 'Create and append new elements dynamically.' },
          { level: 15, title: 'Arrays & Objects', challengeType: 'Coding Challenge', example: 'Display an array of items on a page.' },
          { level: 16, title: 'Fetch API', challengeType: 'Coding Challenge', example: 'Fetch data from an API and display it.' },
          { level: 17, title: 'Form Validation', challengeType: 'Coding Challenge', example: 'Validate a form before submission.' },
          { level: 18, title: 'Local Storage', challengeType: 'Coding Challenge', example: 'Save and retrieve data from local storage.' },
          { level: 19, title: 'ES6+ Features', challengeType: 'Quiz', example: 'Explain arrow functions, destructuring, spread.' },
          { level: 20, title: 'Capstone: Todo App', challengeType: 'Project', example: 'Build a complete todo app with JS.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'React basics and modern web development.',
        goal: 'Build modern web applications.',
        levels: [
          { level: 21, title: 'React Introduction', challengeType: 'Quiz', example: 'What is React and why use it?' },
          { level: 22, title: 'Components & JSX', challengeType: 'Coding Challenge', example: 'Create a React component.' },
          { level: 23, title: 'Props & State', challengeType: 'Coding Challenge', example: 'Pass data using props and manage state.' },
          { level: 24, title: 'Event Handling', challengeType: 'Coding Challenge', example: 'Handle form input changes in React.' },
          { level: 25, title: 'Conditional Rendering', challengeType: 'Coding Challenge', example: 'Show/hide elements based on state.' },
          { level: 26, title: 'Lists & Keys', challengeType: 'Coding Challenge', example: 'Render a list of items from an array.' },
          { level: 27, title: 'useEffect Hook', challengeType: 'Coding Challenge', example: 'Fetch data when component mounts.' },
          { level: 28, title: 'React Router', challengeType: 'Coding Challenge', example: 'Add navigation to a React app.' },
          { level: 29, title: 'State Management', challengeType: 'Coding Challenge', example: 'Use Context API for global state.' },
          { level: 30, title: 'Final Project', challengeType: 'Project', example: 'Build a complete React application.' },
        ],
      },
    ],
  },
  'database-management': {
    slug: 'database-management',
    title: 'Database Management',
    description: 'Learn SQL, database design, and management systems.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSE',
    imageId: 'skill-database',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'SQL basics and queries.',
        goal: 'Write basic SQL queries.',
        levels: [
          { level: 1, title: 'Database Concepts', challengeType: 'Quiz', example: 'What is a relational database?' },
          { level: 2, title: 'Tables & Data Types', challengeType: 'Quiz', example: 'What are common SQL data types?' },
          { level: 3, title: 'CREATE & INSERT', challengeType: 'Simple Exercise', example: 'Create a table and insert records.' },
          { level: 4, title: 'SELECT Queries', challengeType: 'Simple Exercise', example: 'Query all records from a table.' },
          { level: 5, title: 'WHERE Clause', challengeType: 'Simple Exercise', example: 'Filter records using WHERE conditions.' },
          { level: 6, title: 'ORDER BY & LIMIT', challengeType: 'Simple Exercise', example: 'Sort results and limit output.' },
          { level: 7, title: 'UPDATE & DELETE', challengeType: 'Simple Exercise', example: 'Modify and remove records.' },
          { level: 8, title: 'Aggregate Functions', challengeType: 'Simple Exercise', example: 'Use COUNT, SUM, AVG, MAX, MIN.' },
          { level: 9, title: 'GROUP BY & HAVING', challengeType: 'Simple Exercise', example: 'Group results and filter groups.' },
          { level: 10, title: 'Capstone: Tier 1', challengeType: 'Simple Exercise', example: 'Write 5 queries for a students database.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'JOINs and database design.',
        goal: 'Design normalized databases.',
        levels: [
          { level: 11, title: 'INNER JOIN', challengeType: 'Coding Challenge', example: 'Join two tables on a common column.' },
          { level: 12, title: 'LEFT & RIGHT JOIN', challengeType: 'Coding Challenge', example: 'Use outer joins to include unmatched rows.' },
          { level: 13, title: 'Self JOIN', challengeType: 'Coding Challenge', example: 'Join a table with itself.' },
          { level: 14, title: 'Subqueries', challengeType: 'Coding Challenge', example: 'Use a subquery in WHERE clause.' },
          { level: 15, title: 'Normalization: 1NF-3NF', challengeType: 'Quiz', example: 'Explain first three normal forms.' },
          { level: 16, title: 'Primary & Foreign Keys', challengeType: 'Quiz', example: 'What are constraints in SQL?' },
          { level: 17, title: 'ER Diagrams', challengeType: 'Design', example: 'Design an ER diagram for a library system.' },
          { level: 18, title: 'Indexes', challengeType: 'Quiz', example: 'Why and when to use indexes?' },
          { level: 19, title: 'Views', challengeType: 'Coding Challenge', example: 'Create a view for complex query.' },
          { level: 20, title: 'Capstone: Database Design', challengeType: 'Project', example: 'Design a complete e-commerce database.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced SQL and NoSQL.',
        goal: 'Be database proficient.',
        levels: [
          { level: 21, title: 'Stored Procedures', challengeType: 'Coding Challenge', example: 'Create a stored procedure.' },
          { level: 22, title: 'Triggers', challengeType: 'Coding Challenge', example: 'Create a trigger for audit logging.' },
          { level: 23, title: 'Transactions', challengeType: 'Quiz', example: 'Explain ACID properties.' },
          { level: 24, title: 'Query Optimization', challengeType: 'Coding Challenge', example: 'Optimize a slow query.' },
          { level: 25, title: 'NoSQL Introduction', challengeType: 'Quiz', example: 'Difference between SQL and NoSQL.' },
          { level: 26, title: 'MongoDB Basics', challengeType: 'Coding Challenge', example: 'Perform CRUD in MongoDB.' },
          { level: 27, title: 'Document Design', challengeType: 'Design', example: 'Design a MongoDB schema.' },
          { level: 28, title: 'Database Security', challengeType: 'Quiz', example: 'Best practices for database security.' },
          { level: 29, title: 'Backup & Recovery', challengeType: 'Quiz', example: 'Strategies for database backup.' },
          { level: 30, title: 'Final Project', challengeType: 'Project', example: 'Build a full-stack app with database.' },
        ],
      },
    ],
  },
  'machine-learning-basics': {
    slug: 'machine-learning-basics',
    title: 'Machine Learning Basics',
    description: 'Introduction to ML algorithms, model training, and evaluation.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSM',
    imageId: 'skill-ml',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'ML concepts and data preprocessing.',
        goal: 'Understand ML fundamentals.',
        levels: [
          { level: 1, title: 'What is Machine Learning?', challengeType: 'Quiz', example: 'Define ML and its types.' },
          { level: 2, title: 'Supervised vs Unsupervised', challengeType: 'Quiz', example: 'Explain the difference with examples.' },
          { level: 3, title: 'Data Collection', challengeType: 'Simple Exercise', example: 'Load a dataset using pandas.' },
          { level: 4, title: 'Data Exploration', challengeType: 'Simple Exercise', example: 'Explore dataset statistics and info.' },
          { level: 5, title: 'Handling Missing Data', challengeType: 'Simple Exercise', example: 'Fill or drop missing values.' },
          { level: 6, title: 'Feature Scaling', challengeType: 'Simple Exercise', example: 'Apply normalization or standardization.' },
          { level: 7, title: 'Encoding Categories', challengeType: 'Simple Exercise', example: 'One-hot encode categorical features.' },
          { level: 8, title: 'Train-Test Split', challengeType: 'Simple Exercise', example: 'Split data into training and testing sets.' },
          { level: 9, title: 'Model Evaluation Basics', challengeType: 'Quiz', example: 'What are accuracy, precision, recall?' },
          { level: 10, title: 'Capstone: Data Prep', challengeType: 'Project', example: 'Prepare a dataset for ML.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'ML algorithms and model building.',
        goal: 'Build and train ML models.',
        levels: [
          { level: 11, title: 'Linear Regression', challengeType: 'Coding Challenge', example: 'Implement linear regression from scratch.' },
          { level: 12, title: 'Logistic Regression', challengeType: 'Coding Challenge', example: 'Build a classification model.' },
          { level: 13, title: 'Decision Trees', challengeType: 'Coding Challenge', example: 'Train a decision tree classifier.' },
          { level: 14, title: 'Random Forests', challengeType: 'Coding Challenge', example: 'Build an ensemble model.' },
          { level: 15, title: 'K-Nearest Neighbors', challengeType: 'Coding Challenge', example: 'Implement KNN classifier.' },
          { level: 16, title: 'Support Vector Machines', challengeType: 'Coding Challenge', example: 'Train an SVM model.' },
          { level: 17, title: 'Model Evaluation', challengeType: 'Coding Challenge', example: 'Calculate precision, recall, F1-score.' },
          { level: 18, title: 'Cross-Validation', challengeType: 'Coding Challenge', example: 'Perform k-fold cross-validation.' },
          { level: 19, title: 'Hyperparameter Tuning', challengeType: 'Coding Challenge', example: 'Use GridSearchCV for tuning.' },
          { level: 20, title: 'Capstone: Classification', challengeType: 'Project', example: 'Build a complete classification pipeline.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced ML and deployment.',
        goal: 'Deploy ML models.',
        levels: [
          { level: 21, title: 'K-Means Clustering', challengeType: 'Coding Challenge', example: 'Implement k-means clustering.' },
          { level: 22, title: 'PCA', challengeType: 'Coding Challenge', example: 'Apply dimensionality reduction.' },
          { level: 23, title: 'Ensemble Methods', challengeType: 'Coding Challenge', example: 'Build a boosting model (XGBoost).' },
          { level: 24, title: 'Feature Engineering', challengeType: 'Coding Challenge', example: 'Create new features from existing data.' },
          { level: 25, title: 'Model Persistence', challengeType: 'Coding Challenge', example: 'Save and load models with joblib.' },
          { level: 26, title: 'Flask API for ML', challengeType: 'Coding Challenge', example: 'Create an API endpoint for predictions.' },
          { level: 27, title: 'Model Monitoring', challengeType: 'Quiz', example: 'How to monitor model performance?' },
          { level: 28, title: 'MLOps Introduction', challengeType: 'Quiz', example: 'What is MLOps and its components?' },
          { level: 29, title: 'End-to-End Pipeline', challengeType: 'Project', example: 'Build a complete ML pipeline.' },
          { level: 30, title: 'Final Project', challengeType: 'Project', example: 'Deploy an ML model to production.' },
        ],
      },
    ],
  },
  'deep-learning-neural-networks': {
    slug: 'deep-learning-neural-networks',
    title: 'Deep Learning & Neural Networks',
    description: 'Build and train neural networks for complex AI tasks.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSM',
    imageId: 'skill-dl',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Neural network basics.',
        goal: 'Understand neural networks.',
        levels: [
          { level: 1, title: 'What is Deep Learning?', challengeType: 'Quiz', example: 'Define DL and its applications.' },
          { level: 2, title: 'Perceptron', challengeType: 'Quiz', example: 'Explain the perceptron model.' },
          { level: 3, title: 'Activation Functions', challengeType: 'Quiz', example: 'List and explain activation functions.' },
          { level: 4, title: 'Forward Propagation', challengeType: 'Coding Challenge', example: 'Implement forward pass manually.' },
          { level: 5, title: 'Loss Functions', challengeType: 'Quiz', example: 'What are MSE and cross-entropy?' },
          { level: 6, title: 'Backpropagation', challengeType: 'Quiz', example: 'Explain the backprop algorithm.' },
          { level: 7, title: 'Gradient Descent', challengeType: 'Coding Challenge', example: 'Implement gradient descent.' },
          { level: 8, title: 'TensorFlow/PyTorch Basics', challengeType: 'Simple Exercise', example: 'Create tensors and basic operations.' },
          { level: 9, title: 'Building a Simple NN', challengeType: 'Coding Challenge', example: 'Build a 2-layer neural network.' },
          { level: 10, title: 'Capstone: XOR Problem', challengeType: 'Project', example: 'Solve XOR with a neural network.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'CNNs and practical deep learning.',
        goal: 'Build deep learning models.',
        levels: [
          { level: 11, title: 'CNN Introduction', challengeType: 'Quiz', example: 'What are CNNs and their layers?' },
          { level: 12, title: 'Convolution Operations', challengeType: 'Coding Challenge', example: 'Apply convolution to an image.' },
          { level: 13, title: 'Pooling Layers', challengeType: 'Quiz', example: 'Explain max pooling and average pooling.' },
          { level: 14, title: 'Building a CNN', challengeType: 'Coding Challenge', example: 'Build a CNN for image classification.' },
          { level: 15, title: 'Transfer Learning', challengeType: 'Coding Challenge', example: 'Use a pre-trained model (VGG/ResNet).' },
          { level: 16, title: 'Data Augmentation', challengeType: 'Coding Challenge', example: 'Apply augmentation to training data.' },
          { level: 17, title: 'Regularization', challengeType: 'Quiz', example: 'What are dropout and batch normalization?' },
          { level: 18, title: 'Optimizers', challengeType: 'Quiz', example: 'Compare SGD, Adam, RMSprop.' },
          { level: 19, title: 'Model Debugging', challengeType: 'Coding Challenge', example: 'Debug a poorly performing model.' },
          { level: 20, title: 'Capstone: Image Classification', challengeType: 'Project', example: 'Build a complete image classifier.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced architectures.',
        goal: 'Master deep learning.',
        levels: [
          { level: 21, title: 'RNN Introduction', challengeType: 'Quiz', example: 'What are RNNs for sequence data?' },
          { level: 22, title: 'LSTM & GRU', challengeType: 'Coding Challenge', example: 'Build an LSTM for text classification.' },
          { level: 23, title: 'Attention Mechanism', challengeType: 'Quiz', example: 'Explain attention in neural networks.' },
          { level: 24, title: 'Transformers', challengeType: 'Quiz', example: 'What is the transformer architecture?' },
          { level: 25, title: 'GANs Introduction', challengeType: 'Quiz', example: 'Explain generative adversarial networks.' },
          { level: 26, title: 'Building a GAN', challengeType: 'Coding Challenge', example: 'Build a simple GAN.' },
          { level: 27, title: 'Object Detection', challengeType: 'Coding Challenge', example: 'Use YOLO for object detection.' },
          { level: 28, title: 'Model Deployment', challengeType: 'Coding Challenge', example: 'Deploy a DL model with TensorFlow Serving.' },
          { level: 29, title: 'Advanced Project', challengeType: 'Project', example: 'Build a custom deep learning solution.' },
          { level: 30, title: 'Final Capstone', challengeType: 'Project', example: 'End-to-end DL project with deployment.' },
        ],
      },
    ],
  },
  'natural-language-processing': {
    slug: 'natural-language-processing',
    title: 'Natural Language Processing',
    description: 'Process and analyze human language with AI techniques.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSM',
    imageId: 'skill-nlp',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Text preprocessing and basics.',
        goal: 'Understand NLP fundamentals.',
        levels: [
          { level: 1, title: 'What is NLP?', challengeType: 'Quiz', example: 'Define NLP and its applications.' },
          { level: 2, title: 'Tokenization', challengeType: 'Simple Exercise', example: 'Tokenize a sentence into words.' },
          { level: 3, title: 'Stop Words Removal', challengeType: 'Simple Exercise', example: 'Remove stop words from text.' },
          { level: 4, title: 'Stemming & Lemmatization', challengeType: 'Simple Exercise', example: 'Apply stemming to words.' },
          { level: 5, title: 'Text Cleaning', challengeType: 'Simple Exercise', example: 'Clean a text corpus.' },
          { level: 6, title: 'Bag of Words', challengeType: 'Coding Challenge', example: 'Create a BoW representation.' },
          { level: 7, title: 'TF-IDF', challengeType: 'Coding Challenge', example: 'Calculate TF-IDF scores.' },
          { level: 8, title: 'Word Embeddings Intro', challengeType: 'Quiz', example: 'What are word embeddings?' },
          { level: 9, title: 'Using Word2Vec', challengeType: 'Coding Challenge', example: 'Load and use Word2Vec embeddings.' },
          { level: 10, title: 'Capstone: Text Preprocessing', challengeType: 'Project', example: 'Build a text preprocessing pipeline.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'NLP applications and models.',
        goal: 'Build NLP applications.',
        levels: [
          { level: 11, title: 'Text Classification', challengeType: 'Coding Challenge', example: 'Build a sentiment classifier.' },
          { level: 12, title: 'Named Entity Recognition', challengeType: 'Coding Challenge', example: 'Extract entities from text.' },
          { level: 13, title: 'POS Tagging', challengeType: 'Coding Challenge', example: 'Tag parts of speech in sentences.' },
          { level: 14, title: 'Language Models', challengeType: 'Quiz', example: 'What are n-gram language models?' },
          { level: 15, title: 'Sequence Models for NLP', challengeType: 'Coding Challenge', example: 'Use LSTM for text classification.' },
          { level: 16, title: 'Attention for NLP', challengeType: 'Coding Challenge', example: 'Implement attention mechanism.' },
          { level: 17, title: 'BERT Introduction', challengeType: 'Quiz', example: 'What is BERT and how does it work?' },
          { level: 18, title: 'Using Hugging Face', challengeType: 'Coding Challenge', example: 'Use transformers library.' },
          { level: 19, title: 'Fine-tuning BERT', challengeType: 'Coding Challenge', example: 'Fine-tune BERT for classification.' },
          { level: 20, title: 'Capstone: Sentiment Analysis', challengeType: 'Project', example: 'Build a complete sentiment analyzer.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced NLP and LLMs.',
        goal: 'Master modern NLP.',
        levels: [
          { level: 21, title: 'Text Generation', challengeType: 'Coding Challenge', example: 'Generate text with GPT.' },
          { level: 22, title: 'Question Answering', challengeType: 'Coding Challenge', example: 'Build a QA system.' },
          { level: 23, title: 'Summarization', challengeType: 'Coding Challenge', example: 'Implement text summarization.' },
          { level: 24, title: 'Machine Translation', challengeType: 'Coding Challenge', example: 'Build a simple translator.' },
          { level: 25, title: 'Chatbot Development', challengeType: 'Coding Challenge', example: 'Create a rule-based chatbot.' },
          { level: 26, title: 'LLM Prompting', challengeType: 'Coding Challenge', example: 'Master prompt engineering.' },
          { level: 27, title: 'RAG Systems', challengeType: 'Coding Challenge', example: 'Build a RAG application.' },
          { level: 28, title: 'LangChain Basics', challengeType: 'Coding Challenge', example: 'Use LangChain for LLM apps.' },
          { level: 29, title: 'Building with LLMs', challengeType: 'Project', example: 'Build an LLM-powered application.' },
          { level: 30, title: 'Final Project', challengeType: 'Project', example: 'Deploy a production NLP system.' },
        ],
      },
    ],
  },
  'network-security': {
    slug: 'network-security',
    title: 'Network Security',
    description: 'Protect networks from cyber threats and vulnerabilities.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSC',
    imageId: 'skill-network-sec',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Networking and security basics.',
        goal: 'Understand network security concepts.',
        levels: [
          { level: 1, title: 'OSI Model', challengeType: 'Quiz', example: 'Explain the 7 layers of OSI model.' },
          { level: 2, title: 'TCP/IP Protocol', challengeType: 'Quiz', example: 'How does TCP/IP work?' },
          { level: 3, title: 'IP Addressing', challengeType: 'Simple Exercise', example: 'Calculate subnet masks.' },
          { level: 4, title: 'Common Network Attacks', challengeType: 'Quiz', example: 'List types of network attacks.' },
          { level: 5, title: 'Firewalls', challengeType: 'Quiz', example: 'What is a firewall and how does it work?' },
          { level: 6, title: 'VPNs', challengeType: 'Quiz', example: 'Explain VPN types and protocols.' },
          { level: 7, title: 'Network Scanning', challengeType: 'Simple Exercise', example: 'Use nmap for network scanning.' },
          { level: 8, title: 'Packet Analysis', challengeType: 'Simple Exercise', example: 'Analyze packets with Wireshark.' },
          { level: 9, title: 'DNS Security', challengeType: 'Quiz', example: 'What are DNS attacks?' },
          { level: 10, title: 'Capstone: Network Analysis', challengeType: 'Project', example: 'Analyze a network capture file.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Security tools and practices.',
        goal: 'Apply security techniques.',
        levels: [
          { level: 11, title: 'IDS/IPS Systems', challengeType: 'Quiz', example: 'What are IDS and IPS?' },
          { level: 12, title: 'SNORT Basics', challengeType: 'Simple Exercise', example: 'Configure basic SNORT rules.' },
          { level: 13, title: 'Vulnerability Scanning', challengeType: 'Simple Exercise', example: 'Use Nessus for scanning.' },
          { level: 14, title: 'Wireless Security', challengeType: 'Quiz', example: 'WPA2 vs WPA3 security.' },
          { level: 15, title: 'SSL/TLS', challengeType: 'Quiz', example: 'How does HTTPS work?' },
          { level: 16, title: 'Certificate Management', challengeType: 'Simple Exercise', example: 'Generate and manage certificates.' },
          { level: 17, title: 'Network Hardening', challengeType: 'Checklist', example: 'Create a network hardening checklist.' },
          { level: 18, title: 'Log Analysis', challengeType: 'Simple Exercise', example: 'Analyze security logs.' },
          { level: 19, title: 'Incident Response', challengeType: 'Scenario', example: 'Respond to a simulated breach.' },
          { level: 20, title: 'Capstone: Security Audit', challengeType: 'Project', example: 'Perform a network security audit.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced security.',
        goal: 'Master network security.',
        levels: [
          { level: 21, title: 'SIEM Systems', challengeType: 'Quiz', example: 'What is SIEM and its components?' },
          { level: 22, title: 'Threat Intelligence', challengeType: 'Quiz', example: 'Sources of threat intelligence.' },
          { level: 23, title: 'Zero Trust Architecture', challengeType: 'Quiz', example: 'Explain zero trust principles.' },
          { level: 24, title: 'Cloud Network Security', challengeType: 'Quiz', example: 'Security in AWS/Azure networks.' },
          { level: 25, title: 'Container Security', challengeType: 'Simple Exercise', example: 'Secure Docker containers.' },
          { level: 26, title: 'Security Automation', challengeType: 'Coding Challenge', example: 'Automate security tasks with Python.' },
          { level: 27, title: 'Penetration Testing', challengeType: 'Practical', example: 'Conduct a basic pen test.' },
          { level: 28, title: 'Security Policies', challengeType: 'Document', example: 'Write a security policy document.' },
          { level: 29, title: 'Compliance & Frameworks', challengeType: 'Quiz', example: 'NIST, ISO 27001, SOC2 basics.' },
          { level: 30, title: 'Final Project', challengeType: 'Project', example: 'Complete security assessment report.' },
        ],
      },
    ],
  },
  'embedded-systems': {
    slug: 'embedded-systems',
    title: 'Embedded Systems',
    description: 'Design and program embedded systems and microcontrollers.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'ECE',
    imageId: 'skill-embedded',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Microcontroller basics.',
        goal: 'Understand embedded systems.',
        levels: [
          { level: 1, title: 'What are Embedded Systems?', challengeType: 'Quiz', example: 'Define embedded systems with examples.' },
          { level: 2, title: 'Microcontroller Architecture', challengeType: 'Quiz', example: 'Explain MCU components.' },
          { level: 3, title: 'GPIO Basics', challengeType: 'Simple Exercise', example: 'Control an LED with GPIO.' },
          { level: 4, title: 'Digital I/O', challengeType: 'Simple Exercise', example: 'Read a button input.' },
          { level: 5, title: 'PWM Basics', challengeType: 'Simple Exercise', example: 'Generate PWM for LED dimming.' },
          { level: 6, title: 'ADC Conversion', challengeType: 'Simple Exercise', example: 'Read analog sensor values.' },
          { level: 7, title: 'Timers & Counters', challengeType: 'Simple Exercise', example: 'Create a timer-based delay.' },
          { level: 8, title: 'Interrupts', challengeType: 'Simple Exercise', example: 'Handle button press with interrupt.' },
          { level: 9, title: 'Memory Types', challengeType: 'Quiz', example: 'RAM vs ROM vs Flash in MCUs.' },
          { level: 10, title: 'Capstone: LED Matrix', challengeType: 'Project', example: 'Build an LED matrix display.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Communication protocols.',
        goal: 'Interface sensors and modules.',
        levels: [
          { level: 11, title: 'UART Communication', challengeType: 'Simple Exercise', example: 'Send data via UART.' },
          { level: 12, title: 'I2C Protocol', challengeType: 'Simple Exercise', example: 'Interface an I2C sensor.' },
          { level: 13, title: 'SPI Protocol', challengeType: 'Simple Exercise', example: 'Connect an SPI device.' },
          { level: 14, title: 'LCD Display', challengeType: 'Simple Exercise', example: 'Display text on LCD.' },
          { level: 15, title: 'Motor Control', challengeType: 'Simple Exercise', example: 'Control DC motor speed.' },
          { level: 16, title: 'Servo Motors', challengeType: 'Simple Exercise', example: 'Control servo position.' },
          { level: 17, title: 'Sensor Integration', challengeType: 'Project', example: 'Build a temperature logger.' },
          { level: 18, title: 'Low Power Design', challengeType: 'Quiz', example: 'Techniques for power efficiency.' },
          { level: 19, title: 'Debugging Techniques', challengeType: 'Practical', example: 'Debug an embedded program.' },
          { level: 20, title: 'Capstone: Weather Station', challengeType: 'Project', example: 'Build a weather monitoring system.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'RTOS and advanced topics.',
        goal: 'Master embedded development.',
        levels: [
          { level: 21, title: 'RTOS Introduction', challengeType: 'Quiz', example: 'What is an RTOS?' },
          { level: 22, title: 'FreeRTOS Basics', challengeType: 'Simple Exercise', example: 'Create tasks in FreeRTOS.' },
          { level: 23, title: 'Task Scheduling', challengeType: 'Simple Exercise', example: 'Implement task priorities.' },
          { level: 24, title: 'Semaphores & Mutexes', challengeType: 'Simple Exercise', example: 'Synchronize tasks.' },
          { level: 25, title: 'Queues & Communication', challengeType: 'Simple Exercise', example: 'Pass data between tasks.' },
          { level: 26, title: 'Wireless Communication', challengeType: 'Project', example: 'Add Bluetooth/WiFi to project.' },
          { level: 27, title: 'OTA Updates', challengeType: 'Quiz', example: 'Implement over-the-air updates.' },
          { level: 28, title: 'Security in Embedded', challengeType: 'Quiz', example: 'Secure boot and encryption.' },
          { level: 29, title: 'IoT Integration', challengeType: 'Project', example: 'Connect to cloud platform.' },
          { level: 30, title: 'Final Project', challengeType: 'Project', example: 'Build a complete IoT device.' },
        ],
      },
    ],
  },
  'public-speaking-mastery': {
    slug: 'public-speaking-mastery',
    title: 'Public Speaking Mastery',
    description: 'Learn to deliver compelling presentations with confidence.',
    level: 'Beginner',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-public-speaking',
    journey: [
      {
        tier: 1,
        title: 'Awareness',
        focus: 'Theoretical basics of communication, teamwork, confidence.',
        goal: 'Understand key principles.',
        levels: [
          { level: 1, title: 'The 3 Vs of Communication', challengeType: 'Quiz', example: 'What are the three core components of communication?' },
          { level: 2, title: 'Understanding Your Audience', challengeType: 'Scenario-based Choice', example: 'How would you tailor a speech for engineers vs. artists?' },
          { level: 3, title: 'Structuring a Speech', challengeType: 'Quiz', example: 'What are the key parts of a compelling presentation?' },
          { level: 4, title: 'Overcoming Stage Fright', challengeType: 'Scenario-based Choice', example: 'You feel nervous before a talk. What is the best first step?' },
          { level: 5, title: 'The Role of Body Language', challengeType: 'Quiz', example: 'What does open body language signify?' },
          { level: 6, title: 'Handling Difficult Questions', challengeType: 'Scenario-based Choice', example: 'An audience member asks a hostile question. What do you do?' },
          { level: 7, title: 'Basics of Storytelling', challengeType: 'Quiz', example: 'Why are stories effective in presentations?' },
          { level: 8, title: 'Active Listening in a Team', challengeType: 'Scenario-based Choice', example: 'In a team meeting, two members fight. What would you do?' },
          { level: 9, title: 'Giving Constructive Feedback', challengeType: 'Quiz', example: 'What is the "sandwich method" for giving feedback?' },
          { level: 10, title: 'Capstone: Tier 1', challengeType: 'Scenario-based Choice', example: 'Outline a 3-minute talk for a mixed audience.' },
        ],
      },
      {
        tier: 2,
        title: 'Practice',
        focus: 'Apply skills in AI-driven practice.',
        goal: 'Practice real-world scenarios.',
        levels: [
          { level: 11, title: 'Record a Self-Introduction', challengeType: 'Audio Recording', example: 'Record a 30-second audio clip introducing yourself.' },
          { level: 12, title: 'The Elevator Pitch', challengeType: 'Audio Recording', example: 'Record a 60-second pitch about your final-year project.' },
          { level: 13, title: 'Pace and Filler Words', challengeType: 'Audio Recording', example: 'Read a paragraph; AI will analyze your pace and count filler words.' },
          { level: 14, title: 'Virtual Interview: Strengths', challengeType: 'Interview Q&A', example: 'Answer the question: "What are your biggest strengths?"' },
          { level: 15, title: 'Virtual Interview: Weaknesses', challengeType: 'Interview Q&A', example: 'Answer the question: "What is your greatest weakness?"' },
          { level: 16, title: 'Teamwork Simulation I', challengeType: 'Teamwork Simulation', example: 'An AI teammate disagrees with your idea. Persuade them.' },
          { level: 17, title: 'Explaining a Technical Concept', challengeType: 'Video Recording', example: 'Record a 2-minute video explaining a simple technical topic.' },
          { level: 18, title: 'Body Language Analysis', challengeType: 'Video Recording', example: 'Deliver a short speech; AI will analyze your posture and gestures.' },
          { level: 19, title: 'Impromptu Speaking I', challengeType: 'Audio Recording', example: 'Speak for 60 seconds on a random topic given by the AI.' },
          { level: 20, title: 'Capstone: Tier 2', challengeType: 'Video Recording', example: 'Record a 3-minute presentation on a topic of your choice.' },
        ],
      },
      {
        tier: 3,
        title: 'Advanced Scenarios',
        focus: 'Leadership, adaptability, handling pressure.',
        goal: 'Become workplace-ready.',
        levels: [
          { level: 21, title: 'Debate Simulation', challengeType: 'Debate', example: 'Debate against an AI on a given topic.' },
          { level: 22, title: 'Presentation with Q&A', challengeType: 'Presentation', example: 'Deliver a 5-min presentation; AI asks 3 tough questions.' },
          { level: 23, title: 'Negotiation Simulation', challengeType: 'Negotiation', example: 'Negotiate a project deadline with an AI project manager.' },
          { level: 24, title: 'Handling a "Hostile" Audience', challengeType: 'Presentation', example: 'Present an unpopular opinion and defend it against AI counter-arguments.' },
          { level: 25, title: 'Crisis Communication', challengeType: 'Simulation', example: 'An AI simulates a project crisis. Deliver a calming and clear update.' },
          { level: 26, title: 'Leading a Team Meeting', challengeType: 'Simulation', example: 'Lead a simulated meeting with two AI teammates to a decision.' },
          { level: 27, title: 'Persuasive Storytelling', challengeType: 'Presentation', example: 'Craft and deliver a persuasive story with a clear call to action.' },
          { level: 28, title: 'Adapting on the Fly', challengeType: 'Presentation', example: 'The AI will interrupt your presentation with a major change. Adapt your talk.' },
          { level: 29, title: 'Keynote Address Practice', challengeType: 'Presentation', example: 'Deliver the opening of a 10-minute keynote speech.' },
          { level: 30, title: 'Final Capstone Project', challengeType: 'Real-world Project', example: 'Prepare and deliver a full 10-minute presentation with slides and handle a live Q&A with the AI.' },
        ],
      },
    ],
  },
  'interview-preparation': {
    slug: 'interview-preparation',
    title: 'Interview Preparation',
    description: 'Prepare for technical and HR interviews with confidence.',
    level: 'Beginner',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-interview',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Interview basics and resume building.',
        goal: 'Understand interview process.',
        levels: [
          { level: 1, title: 'Types of Interviews', challengeType: 'Quiz', example: 'What are different types of interviews?' },
          { level: 2, title: 'Resume Writing', challengeType: 'Exercise', example: 'List key sections of a good resume.' },
          { level: 3, title: 'ATS Optimization', challengeType: 'Quiz', example: 'How to make resume ATS-friendly?' },
          { level: 4, title: 'Research the Company', challengeType: 'Exercise', example: 'What to research before an interview?' },
          { level: 5, title: 'Common HR Questions', challengeType: 'Practice', example: 'Answer "Tell me about yourself".' },
          { level: 6, title: 'STAR Method', challengeType: 'Quiz', example: 'Explain the STAR method for answers.' },
          { level: 7, title: 'Behavioral Questions', challengeType: 'Practice', example: 'Describe a challenge you overcame.' },
          { level: 8, title: 'Body Language', challengeType: 'Quiz', example: 'Best practices for interview body language.' },
          { level: 9, title: 'Virtual Interviews', challengeType: 'Quiz', example: 'Tips for video call interviews.' },
          { level: 10, title: 'Capstone: Mock HR Interview', challengeType: 'Practice', example: 'Complete a mock HR interview.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Technical interview preparation.',
        goal: 'Handle technical rounds.',
        levels: [
          { level: 11, title: 'Technical Interview Format', challengeType: 'Quiz', example: 'What to expect in technical rounds?' },
          { level: 12, title: 'Problem Solving Approach', challengeType: 'Practice', example: 'How to approach coding problems?' },
          { level: 13, title: 'Thinking Aloud', challengeType: 'Practice', example: 'Practice explaining your thought process.' },
          { level: 14, title: 'Handling Unknown Questions', challengeType: 'Scenario', example: 'What to do when stuck on a problem?' },
          { level: 15, title: 'Code Review Skills', challengeType: 'Practice', example: 'Review and explain given code.' },
          { level: 16, title: 'System Design Basics', challengeType: 'Quiz', example: 'What is asked in system design rounds?' },
          { level: 17, title: 'Project Discussion', challengeType: 'Practice', example: 'Explain your best project clearly.' },
          { level: 18, title: 'Questions to Ask', challengeType: 'Quiz', example: 'Good questions to ask interviewer.' },
          { level: 19, title: 'Handling Rejection', challengeType: 'Quiz', example: 'How to learn from interview rejections?' },
          { level: 20, title: 'Capstone: Mock Technical', challengeType: 'Practice', example: 'Complete a mock technical interview.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced interview skills.',
        goal: 'Ace any interview.',
        levels: [
          { level: 21, title: 'Salary Negotiation', challengeType: 'Scenario', example: 'How to negotiate salary effectively?' },
          { level: 22, title: 'Multiple Offers', challengeType: 'Scenario', example: 'How to handle multiple job offers?' },
          { level: 23, title: 'Culture Fit Questions', challengeType: 'Practice', example: 'Answer culture fit questions.' },
          { level: 24, title: 'Leadership Questions', challengeType: 'Practice', example: 'Demonstrate leadership in answers.' },
          { level: 25, title: 'Panel Interviews', challengeType: 'Quiz', example: 'Tips for panel interview success.' },
          { level: 26, title: 'Case Studies', challengeType: 'Practice', example: 'Solve a business case study.' },
          { level: 27, title: 'Group Discussions', challengeType: 'Practice', example: 'Strategies for GD rounds.' },
          { level: 28, title: 'Follow-up Etiquette', challengeType: 'Quiz', example: 'Best practices for post-interview.' },
          { level: 29, title: 'Building Your Brand', challengeType: 'Exercise', example: 'Create your personal brand statement.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'Complete full mock interview process.' },
        ],
      },
    ],
  },
  'data-visualization': {
    slug: 'data-visualization',
    title: 'Data Visualization',
    description: 'Create compelling visualizations to tell data stories.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSD',
    imageId: 'skill-dataviz',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Basic charts, color theory, visualization principles.',
        goal: 'Understand visualization fundamentals.',
        levels: [
          { level: 1, title: 'Why Visualize?', challengeType: 'Quiz', example: 'When should you use charts vs tables?' },
          { level: 2, title: 'Chart Types', challengeType: 'Quiz', example: 'Match data types to appropriate charts.' },
          { level: 3, title: 'Bar Charts', challengeType: 'Exercise', example: 'Create a bar chart from given data.' },
          { level: 4, title: 'Line Charts', challengeType: 'Exercise', example: 'Plot time series data.' },
          { level: 5, title: 'Pie Charts', challengeType: 'Quiz', example: 'When are pie charts appropriate?' },
          { level: 6, title: 'Color Theory', challengeType: 'Quiz', example: 'Choose accessible color palettes.' },
          { level: 7, title: 'Labels & Titles', challengeType: 'Exercise', example: 'Add proper labels to a chart.' },
          { level: 8, title: 'Matplotlib Basics', challengeType: 'Coding', example: 'Create a simple plot with Matplotlib.' },
          { level: 9, title: 'Customizing Plots', challengeType: 'Coding', example: 'Change colors, fonts, and styles.' },
          { level: 10, title: 'Capstone: Basic Dashboard', challengeType: 'Project', example: 'Create a simple multi-chart dashboard.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Advanced charts, interactive visualizations.',
        goal: 'Create professional visualizations.',
        levels: [
          { level: 11, title: 'Scatter Plots', challengeType: 'Coding', example: 'Visualize correlations with scatter plots.' },
          { level: 12, title: 'Histograms', challengeType: 'Coding', example: 'Show distribution of data.' },
          { level: 13, title: 'Box Plots', challengeType: 'Coding', example: 'Compare distributions across groups.' },
          { level: 14, title: 'Heatmaps', challengeType: 'Coding', example: 'Visualize correlation matrices.' },
          { level: 15, title: 'Seaborn Library', challengeType: 'Coding', example: 'Create statistical visualizations.' },
          { level: 16, title: 'Plotly Introduction', challengeType: 'Coding', example: 'Create interactive charts.' },
          { level: 17, title: 'Geographic Maps', challengeType: 'Coding', example: 'Plot data on maps.' },
          { level: 18, title: 'Dashboard Design', challengeType: 'Quiz', example: 'Principles of dashboard layout.' },
          { level: 19, title: 'Storytelling with Data', challengeType: 'Exercise', example: 'Create a data narrative.' },
          { level: 20, title: 'Capstone: Interactive Report', challengeType: 'Project', example: 'Build an interactive data report.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced tools, real-world applications.',
        goal: 'Create publication-ready visualizations.',
        levels: [
          { level: 21, title: 'Tableau Basics', challengeType: 'Tool', example: 'Create your first Tableau viz.' },
          { level: 22, title: 'Power BI', challengeType: 'Tool', example: 'Build a Power BI dashboard.' },
          { level: 23, title: 'D3.js Introduction', challengeType: 'Coding', example: 'Create custom web visualizations.' },
          { level: 24, title: 'Animation in Charts', challengeType: 'Coding', example: 'Add motion to visualizations.' },
          { level: 25, title: 'Big Data Visualization', challengeType: 'Scenario', example: 'Handle millions of data points.' },
          { level: 26, title: 'Real-time Dashboards', challengeType: 'Project', example: 'Create live updating dashboards.' },
          { level: 27, title: 'Accessibility', challengeType: 'Quiz', example: 'Make visualizations accessible to all.' },
          { level: 28, title: 'Publication Standards', challengeType: 'Exercise', example: 'Prepare charts for publication.' },
          { level: 29, title: 'Portfolio Project', challengeType: 'Project', example: 'Create a visualization portfolio.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'Complete end-to-end viz project.' },
        ],
      },
    ],
  },
  'statistical-analysis': {
    slug: 'statistical-analysis',
    title: 'Statistical Analysis',
    description: 'Apply statistical methods to analyze and interpret data.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'CSD',
    imageId: 'skill-stats',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Descriptive statistics, probability basics.',
        goal: 'Understand statistical fundamentals.',
        levels: [
          { level: 1, title: 'Mean, Median, Mode', challengeType: 'Quiz', example: 'Calculate central tendency measures.' },
          { level: 2, title: 'Variance & Std Dev', challengeType: 'Exercise', example: 'Compute spread of data.' },
          { level: 3, title: 'Percentiles', challengeType: 'Exercise', example: 'Find quartiles and percentiles.' },
          { level: 4, title: 'Probability Basics', challengeType: 'Quiz', example: 'Calculate simple probabilities.' },
          { level: 5, title: 'Conditional Probability', challengeType: 'Quiz', example: 'Apply Bayes theorem.' },
          { level: 6, title: 'Normal Distribution', challengeType: 'Exercise', example: 'Work with normal curves.' },
          { level: 7, title: 'Sampling Methods', challengeType: 'Quiz', example: 'Types of sampling techniques.' },
          { level: 8, title: 'Sample vs Population', challengeType: 'Quiz', example: 'Understand sampling concepts.' },
          { level: 9, title: 'Python for Stats', challengeType: 'Coding', example: 'Use scipy for basic stats.' },
          { level: 10, title: 'Capstone: EDA', challengeType: 'Project', example: 'Perform exploratory data analysis.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Hypothesis testing, correlation, regression.',
        goal: 'Apply inferential statistics.',
        levels: [
          { level: 11, title: 'Hypothesis Testing', challengeType: 'Exercise', example: 'Set up null and alternate hypothesis.' },
          { level: 12, title: 'T-Tests', challengeType: 'Coding', example: 'Perform t-tests in Python.' },
          { level: 13, title: 'Chi-Square Tests', challengeType: 'Coding', example: 'Test categorical relationships.' },
          { level: 14, title: 'ANOVA', challengeType: 'Coding', example: 'Compare multiple group means.' },
          { level: 15, title: 'Correlation Analysis', challengeType: 'Exercise', example: 'Calculate Pearson correlation.' },
          { level: 16, title: 'Simple Linear Regression', challengeType: 'Coding', example: 'Fit a line to data.' },
          { level: 17, title: 'Multiple Regression', challengeType: 'Coding', example: 'Use multiple predictors.' },
          { level: 18, title: 'P-values & Significance', challengeType: 'Quiz', example: 'Interpret statistical significance.' },
          { level: 19, title: 'Confidence Intervals', challengeType: 'Exercise', example: 'Calculate and interpret CIs.' },
          { level: 20, title: 'Capstone: A/B Testing', challengeType: 'Project', example: 'Design and analyze an A/B test.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced methods, real-world applications.',
        goal: 'Be a statistical expert.',
        levels: [
          { level: 21, title: 'Logistic Regression', challengeType: 'Coding', example: 'Predict binary outcomes.' },
          { level: 22, title: 'Time Series Analysis', challengeType: 'Coding', example: 'Analyze temporal patterns.' },
          { level: 23, title: 'Bayesian Statistics', challengeType: 'Exercise', example: 'Apply Bayesian inference.' },
          { level: 24, title: 'Non-parametric Tests', challengeType: 'Coding', example: 'Use distribution-free methods.' },
          { level: 25, title: 'Factor Analysis', challengeType: 'Coding', example: 'Reduce dimensionality.' },
          { level: 26, title: 'Survival Analysis', challengeType: 'Coding', example: 'Analyze time-to-event data.' },
          { level: 27, title: 'Power Analysis', challengeType: 'Exercise', example: 'Determine sample sizes.' },
          { level: 28, title: 'Statistical Reporting', challengeType: 'Exercise', example: 'Write statistical reports.' },
          { level: 29, title: 'Case Study', challengeType: 'Project', example: 'Complete a real-world analysis.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'Demonstrate statistical mastery.' },
        ],
      },
    ],
  },
  'ethical-hacking': {
    slug: 'ethical-hacking',
    title: 'Ethical Hacking',
    description: 'Learn penetration testing and security assessment techniques.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSC',
    imageId: 'skill-hacking',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Security basics, reconnaissance, footprinting.',
        goal: 'Understand hacking fundamentals.',
        levels: [
          { level: 1, title: 'Ethics & Legal', challengeType: 'Quiz', example: 'Legal aspects of ethical hacking.' },
          { level: 2, title: 'Hacker Mindset', challengeType: 'Quiz', example: 'How hackers think and approach targets.' },
          { level: 3, title: 'Kali Linux Setup', challengeType: 'Exercise', example: 'Set up your hacking environment.' },
          { level: 4, title: 'Information Gathering', challengeType: 'Exercise', example: 'Gather target information.' },
          { level: 5, title: 'OSINT Techniques', challengeType: 'Exercise', example: 'Use open source intelligence.' },
          { level: 6, title: 'Network Basics', challengeType: 'Quiz', example: 'TCP/IP for hackers.' },
          { level: 7, title: 'Port Scanning', challengeType: 'Coding', example: 'Use Nmap for scanning.' },
          { level: 8, title: 'Service Enumeration', challengeType: 'Exercise', example: 'Identify running services.' },
          { level: 9, title: 'Vulnerability Research', challengeType: 'Exercise', example: 'Find known vulnerabilities.' },
          { level: 10, title: 'Capstone: Recon Report', challengeType: 'Project', example: 'Complete reconnaissance on test target.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Exploitation, web hacking, password attacks.',
        goal: 'Execute common attacks.',
        levels: [
          { level: 11, title: 'Web App Attacks', challengeType: 'Exercise', example: 'Test for common web vulnerabilities.' },
          { level: 12, title: 'SQL Injection', challengeType: 'Lab', example: 'Exploit SQL injection flaws.' },
          { level: 13, title: 'XSS Attacks', challengeType: 'Lab', example: 'Execute cross-site scripting.' },
          { level: 14, title: 'Password Cracking', challengeType: 'Exercise', example: 'Use password cracking tools.' },
          { level: 15, title: 'Metasploit Framework', challengeType: 'Lab', example: 'Use Metasploit for exploitation.' },
          { level: 16, title: 'Social Engineering', challengeType: 'Quiz', example: 'Human-based attack techniques.' },
          { level: 17, title: 'Wireless Hacking', challengeType: 'Exercise', example: 'Test wireless network security.' },
          { level: 18, title: 'Privilege Escalation', challengeType: 'Lab', example: 'Escalate access privileges.' },
          { level: 19, title: 'Maintaining Access', challengeType: 'Quiz', example: 'Persistence techniques.' },
          { level: 20, title: 'Capstone: CTF Challenge', challengeType: 'Project', example: 'Complete a capture the flag challenge.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced exploitation, reporting, defense.',
        goal: 'Be a professional pentester.',
        levels: [
          { level: 21, title: 'Buffer Overflows', challengeType: 'Lab', example: 'Exploit buffer overflow vulnerabilities.' },
          { level: 22, title: 'Advanced Web Attacks', challengeType: 'Lab', example: 'SSRF, XXE, and more.' },
          { level: 23, title: 'Mobile App Testing', challengeType: 'Exercise', example: 'Test mobile applications.' },
          { level: 24, title: 'Cloud Security', challengeType: 'Quiz', example: 'AWS/Azure security testing.' },
          { level: 25, title: 'Red Team Operations', challengeType: 'Scenario', example: 'Plan a red team engagement.' },
          { level: 26, title: 'Writing Exploits', challengeType: 'Coding', example: 'Create custom exploits.' },
          { level: 27, title: 'Report Writing', challengeType: 'Exercise', example: 'Write professional pentest reports.' },
          { level: 28, title: 'Remediation Advice', challengeType: 'Exercise', example: 'Recommend security fixes.' },
          { level: 29, title: 'Bug Bounty', challengeType: 'Project', example: 'Participate in bug bounty programs.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'Complete professional pentest simulation.' },
        ],
      },
    ],
  },
  'cryptography': {
    slug: 'cryptography',
    title: 'Cryptography',
    description: 'Understand encryption, hashing, and secure communication.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'CSC',
    imageId: 'skill-crypto',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Basic cryptography, classical ciphers.',
        goal: 'Understand crypto fundamentals.',
        levels: [
          { level: 1, title: 'History of Crypto', challengeType: 'Quiz', example: 'Evolution of cryptography.' },
          { level: 2, title: 'Caesar Cipher', challengeType: 'Coding', example: 'Implement Caesar cipher.' },
          { level: 3, title: 'Substitution Ciphers', challengeType: 'Exercise', example: 'Break simple substitution.' },
          { level: 4, title: 'Frequency Analysis', challengeType: 'Exercise', example: 'Analyze letter frequencies.' },
          { level: 5, title: 'XOR Operations', challengeType: 'Coding', example: 'Use XOR for encryption.' },
          { level: 6, title: 'Binary & Hex', challengeType: 'Exercise', example: 'Work with different bases.' },
          { level: 7, title: 'Encoding vs Encryption', challengeType: 'Quiz', example: 'Understand the difference.' },
          { level: 8, title: 'Hash Functions', challengeType: 'Coding', example: 'Generate MD5 and SHA hashes.' },
          { level: 9, title: 'Hash Properties', challengeType: 'Quiz', example: 'What makes a good hash?' },
          { level: 10, title: 'Capstone: Cipher Tool', challengeType: 'Project', example: 'Build a cipher encryption tool.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Modern cryptography, symmetric/asymmetric.',
        goal: 'Apply modern crypto techniques.',
        levels: [
          { level: 11, title: 'Symmetric Encryption', challengeType: 'Quiz', example: 'How symmetric crypto works.' },
          { level: 12, title: 'AES Algorithm', challengeType: 'Coding', example: 'Implement AES encryption.' },
          { level: 13, title: 'Block Cipher Modes', challengeType: 'Quiz', example: 'ECB, CBC, CTR modes.' },
          { level: 14, title: 'Asymmetric Encryption', challengeType: 'Quiz', example: 'Public key cryptography basics.' },
          { level: 15, title: 'RSA Algorithm', challengeType: 'Coding', example: 'Implement RSA basics.' },
          { level: 16, title: 'Key Exchange', challengeType: 'Exercise', example: 'Diffie-Hellman key exchange.' },
          { level: 17, title: 'Digital Signatures', challengeType: 'Coding', example: 'Sign and verify messages.' },
          { level: 18, title: 'Certificates & PKI', challengeType: 'Quiz', example: 'How certificates work.' },
          { level: 19, title: 'SSL/TLS', challengeType: 'Exercise', example: 'Understand HTTPS.' },
          { level: 20, title: 'Capstone: Secure Chat', challengeType: 'Project', example: 'Build encrypted messaging.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced crypto, real-world applications.',
        goal: 'Be a cryptography expert.',
        levels: [
          { level: 21, title: 'Elliptic Curves', challengeType: 'Exercise', example: 'ECC fundamentals.' },
          { level: 22, title: 'Password Storage', challengeType: 'Coding', example: 'Secure password hashing.' },
          { level: 23, title: 'Random Number Gen', challengeType: 'Quiz', example: 'Cryptographic randomness.' },
          { level: 24, title: 'Crypto Attacks', challengeType: 'Exercise', example: 'Common crypto vulnerabilities.' },
          { level: 25, title: 'Zero Knowledge Proofs', challengeType: 'Quiz', example: 'Prove without revealing.' },
          { level: 26, title: 'Blockchain Basics', challengeType: 'Exercise', example: 'Crypto in blockchain.' },
          { level: 27, title: 'Post-Quantum Crypto', challengeType: 'Quiz', example: 'Future of cryptography.' },
          { level: 28, title: 'Crypto Libraries', challengeType: 'Coding', example: 'Use professional libraries.' },
          { level: 29, title: 'Security Audit', challengeType: 'Project', example: 'Audit crypto implementation.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'Design secure system.' },
        ],
      },
    ],
  },
  'vlsi-design': {
    slug: 'vlsi-design',
    title: 'VLSI Design',
    description: 'Design integrated circuits and digital systems.',
    level: 'Advanced',
    category: 'Technical',
    branch: 'ECE',
    imageId: 'skill-vlsi',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Digital logic, HDL basics.',
        goal: 'Understand VLSI fundamentals.',
        levels: [
          { level: 1, title: 'Digital Logic Review', challengeType: 'Quiz', example: 'Logic gates and truth tables.' },
          { level: 2, title: 'Boolean Algebra', challengeType: 'Exercise', example: 'Simplify Boolean expressions.' },
          { level: 3, title: 'Combinational Circuits', challengeType: 'Exercise', example: 'Design a multiplexer.' },
          { level: 4, title: 'Sequential Circuits', challengeType: 'Exercise', example: 'Design flip-flops.' },
          { level: 5, title: 'Verilog Introduction', challengeType: 'Coding', example: 'Write your first Verilog module.' },
          { level: 6, title: 'Verilog Data Types', challengeType: 'Quiz', example: 'Wire vs reg in Verilog.' },
          { level: 7, title: 'Behavioral Modeling', challengeType: 'Coding', example: 'Always blocks in Verilog.' },
          { level: 8, title: 'Structural Modeling', challengeType: 'Coding', example: 'Module instantiation.' },
          { level: 9, title: 'Testbenches', challengeType: 'Coding', example: 'Write a simple testbench.' },
          { level: 10, title: 'Capstone: ALU Design', challengeType: 'Project', example: 'Design a basic ALU.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Advanced HDL, synthesis, timing.',
        goal: 'Design complex digital systems.',
        levels: [
          { level: 11, title: 'FSM Design', challengeType: 'Coding', example: 'Design a state machine.' },
          { level: 12, title: 'Memory Design', challengeType: 'Coding', example: 'Design RAM in Verilog.' },
          { level: 13, title: 'FIFO Implementation', challengeType: 'Coding', example: 'Design a FIFO buffer.' },
          { level: 14, title: 'Clock Domains', challengeType: 'Quiz', example: 'Crossing clock domains.' },
          { level: 15, title: 'Timing Analysis', challengeType: 'Exercise', example: 'Setup and hold times.' },
          { level: 16, title: 'Synthesis Basics', challengeType: 'Exercise', example: 'RTL to gate level.' },
          { level: 17, title: 'FPGA Introduction', challengeType: 'Quiz', example: 'FPGA architecture.' },
          { level: 18, title: 'FPGA Implementation', challengeType: 'Lab', example: 'Implement on FPGA.' },
          { level: 19, title: 'Verification Basics', challengeType: 'Quiz', example: 'Verification methodology.' },
          { level: 20, title: 'Capstone: Processor', challengeType: 'Project', example: 'Design a simple processor.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'ASIC flow, advanced verification.',
        goal: 'Be a VLSI design expert.',
        levels: [
          { level: 21, title: 'SystemVerilog', challengeType: 'Coding', example: 'Advanced SV features.' },
          { level: 22, title: 'UVM Basics', challengeType: 'Exercise', example: 'UVM testbench structure.' },
          { level: 23, title: 'Assertions', challengeType: 'Coding', example: 'Write SVA assertions.' },
          { level: 24, title: 'Coverage', challengeType: 'Exercise', example: 'Functional coverage.' },
          { level: 25, title: 'Low Power Design', challengeType: 'Quiz', example: 'Power optimization techniques.' },
          { level: 26, title: 'Physical Design', challengeType: 'Quiz', example: 'Floor planning basics.' },
          { level: 27, title: 'DFT Concepts', challengeType: 'Quiz', example: 'Design for testability.' },
          { level: 28, title: 'Industry Tools', challengeType: 'Exercise', example: 'EDA tool overview.' },
          { level: 29, title: 'Chip Design Project', challengeType: 'Project', example: 'Complete chip design.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'Full VLSI design cycle.' },
        ],
      },
    ],
  },
  'iot-development': {
    slug: 'iot-development',
    title: 'IoT Development',
    description: 'Build connected devices and IoT systems.',
    level: 'Intermediate',
    category: 'Technical',
    branch: 'ECE',
    imageId: 'skill-iot',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'IoT basics, sensors, microcontrollers.',
        goal: 'Understand IoT fundamentals.',
        levels: [
          { level: 1, title: 'What is IoT?', challengeType: 'Quiz', example: 'IoT architecture and applications.' },
          { level: 2, title: 'Sensors Overview', challengeType: 'Quiz', example: 'Types of sensors.' },
          { level: 3, title: 'Arduino Basics', challengeType: 'Lab', example: 'Blink an LED.' },
          { level: 4, title: 'Digital I/O', challengeType: 'Lab', example: 'Read buttons, control LEDs.' },
          { level: 5, title: 'Analog Sensors', challengeType: 'Lab', example: 'Read temperature sensor.' },
          { level: 6, title: 'Serial Communication', challengeType: 'Lab', example: 'Print sensor data.' },
          { level: 7, title: 'ESP32 Introduction', challengeType: 'Lab', example: 'Setup ESP32 board.' },
          { level: 8, title: 'WiFi Connection', challengeType: 'Lab', example: 'Connect ESP32 to WiFi.' },
          { level: 9, title: 'Basic Web Server', challengeType: 'Lab', example: 'Create simple web interface.' },
          { level: 10, title: 'Capstone: Smart Sensor', challengeType: 'Project', example: 'Build web-connected sensor.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Protocols, cloud, data management.',
        goal: 'Build complete IoT systems.',
        levels: [
          { level: 11, title: 'MQTT Protocol', challengeType: 'Lab', example: 'Publish and subscribe.' },
          { level: 12, title: 'HTTP APIs', challengeType: 'Lab', example: 'Send data to cloud.' },
          { level: 13, title: 'Cloud Platforms', challengeType: 'Lab', example: 'Setup AWS IoT or similar.' },
          { level: 14, title: 'Data Visualization', challengeType: 'Lab', example: 'Create IoT dashboard.' },
          { level: 15, title: 'Bluetooth LE', challengeType: 'Lab', example: 'BLE communication.' },
          { level: 16, title: 'LoRa/LoRaWAN', challengeType: 'Quiz', example: 'Long range communication.' },
          { level: 17, title: 'Power Management', challengeType: 'Exercise', example: 'Battery optimization.' },
          { level: 18, title: 'OTA Updates', challengeType: 'Lab', example: 'Remote firmware update.' },
          { level: 19, title: 'Data Security', challengeType: 'Quiz', example: 'Secure IoT communication.' },
          { level: 20, title: 'Capstone: Smart Home', challengeType: 'Project', example: 'Build home automation system.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced IoT, edge computing, AI.',
        goal: 'Be an IoT expert.',
        levels: [
          { level: 21, title: 'Edge Computing', challengeType: 'Exercise', example: 'Process data at edge.' },
          { level: 22, title: 'TinyML', challengeType: 'Lab', example: 'Run ML on microcontrollers.' },
          { level: 23, title: 'Industrial IoT', challengeType: 'Quiz', example: 'IIoT applications.' },
          { level: 24, title: 'Digital Twins', challengeType: 'Exercise', example: 'Create digital twin.' },
          { level: 25, title: 'IoT Security', challengeType: 'Exercise', example: 'Secure device lifecycle.' },
          { level: 26, title: 'Mesh Networks', challengeType: 'Lab', example: 'Build mesh network.' },
          { level: 27, title: 'Custom PCB Design', challengeType: 'Exercise', example: 'Design IoT PCB.' },
          { level: 28, title: 'Production Scaling', challengeType: 'Quiz', example: 'Mass production considerations.' },
          { level: 29, title: 'Full IoT Product', challengeType: 'Project', example: 'Complete product development.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'End-to-end IoT system.' },
        ],
      },
    ],
  },
  'technical-writing': {
    slug: 'technical-writing',
    title: 'Technical Writing',
    description: 'Write clear documentation, reports, and technical content.',
    level: 'Beginner',
    category: 'Soft Skill',
    branch: 'General',
    imageId: 'skill-writing',
    journey: [
      {
        tier: 1,
        title: 'Foundation',
        focus: 'Writing basics, clarity, structure.',
        goal: 'Write clear technical content.',
        levels: [
          { level: 1, title: 'Why Technical Writing?', challengeType: 'Quiz', example: 'Importance of documentation.' },
          { level: 2, title: 'Know Your Audience', challengeType: 'Quiz', example: 'Writing for different readers.' },
          { level: 3, title: 'Active Voice', challengeType: 'Exercise', example: 'Convert passive to active.' },
          { level: 4, title: 'Concise Writing', challengeType: 'Exercise', example: 'Reduce wordiness.' },
          { level: 5, title: 'Sentence Structure', challengeType: 'Exercise', example: 'Write clear sentences.' },
          { level: 6, title: 'Paragraph Organization', challengeType: 'Exercise', example: 'Structure paragraphs.' },
          { level: 7, title: 'Headings & Lists', challengeType: 'Exercise', example: 'Use formatting effectively.' },
          { level: 8, title: 'Technical Terminology', challengeType: 'Quiz', example: 'When to use jargon.' },
          { level: 9, title: 'Grammar Essentials', challengeType: 'Quiz', example: 'Common grammar issues.' },
          { level: 10, title: 'Capstone: Blog Post', challengeType: 'Project', example: 'Write a technical blog.' },
        ],
      },
      {
        tier: 2,
        title: 'Application',
        focus: 'Documentation types, tools.',
        goal: 'Create professional documentation.',
        levels: [
          { level: 11, title: 'README Files', challengeType: 'Exercise', example: 'Write a good README.' },
          { level: 12, title: 'API Documentation', challengeType: 'Exercise', example: 'Document an API.' },
          { level: 13, title: 'User Guides', challengeType: 'Exercise', example: 'Write step-by-step guides.' },
          { level: 14, title: 'Tutorials', challengeType: 'Exercise', example: 'Create a tutorial.' },
          { level: 15, title: 'Code Comments', challengeType: 'Exercise', example: 'Write effective comments.' },
          { level: 16, title: 'Markdown Mastery', challengeType: 'Coding', example: 'Format with Markdown.' },
          { level: 17, title: 'Documentation Tools', challengeType: 'Quiz', example: 'Docs-as-code tools.' },
          { level: 18, title: 'Style Guides', challengeType: 'Quiz', example: 'Following style guides.' },
          { level: 19, title: 'Review & Editing', challengeType: 'Exercise', example: 'Edit technical content.' },
          { level: 20, title: 'Capstone: Doc Site', challengeType: 'Project', example: 'Create documentation site.' },
        ],
      },
      {
        tier: 3,
        title: 'Mastery',
        focus: 'Advanced docs, information architecture.',
        goal: 'Be a technical writing expert.',
        levels: [
          { level: 21, title: 'Information Architecture', challengeType: 'Exercise', example: 'Organize large doc sets.' },
          { level: 22, title: 'Release Notes', challengeType: 'Exercise', example: 'Write release notes.' },
          { level: 23, title: 'Error Messages', challengeType: 'Exercise', example: 'Write helpful error messages.' },
          { level: 24, title: 'Localization', challengeType: 'Quiz', example: 'Writing for translation.' },
          { level: 25, title: 'Accessibility', challengeType: 'Quiz', example: 'Accessible documentation.' },
          { level: 26, title: 'Visual Content', challengeType: 'Exercise', example: 'Diagrams and screenshots.' },
          { level: 27, title: 'Video Scripts', challengeType: 'Exercise', example: 'Write video tutorials.' },
          { level: 28, title: 'Portfolio Building', challengeType: 'Project', example: 'Build writing portfolio.' },
          { level: 29, title: 'Industry Practices', challengeType: 'Quiz', example: 'Modern tech writing.' },
          { level: 30, title: 'Final Assessment', challengeType: 'Comprehensive', example: 'Complete documentation project.' },
        ],
      },
    ],
  },
};

// Helper function to get skill track by slug
export function getSkillTrack(slug: string): SkillTrack | undefined {
  return skillsData[slug];
}

// Helper function to get skills by branch
export function getSkillsByBranch(branch: Branch): Omit<SkillTrack, 'journey'>[] {
  return skillTracks.filter(track => track.branch === branch || track.branch === 'General');
}

// Helper function to get all available branches with skill counts
export function getBranchesWithCounts(): { branch: Branch; name: string; count: number }[] {
  return branches.map(b => ({
    branch: b.id,
    name: b.name,
    count: skillTracks.filter(t => t.branch === b.id).length,
  }));
}
