"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { motion, AnimatePresence } from "framer-motion";
import {
  createPersonalizedStudyPlan,
  type CreatePersonalizedStudyPlanOutput,
} from "@/ai/flows/create-personalized-study-plan";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import {
  Loader2,
  AlertTriangle,
  Target,
  Calendar,
  Clock,
  Rocket,
  Download,
  BookOpen,
  Sparkles,
  CheckCircle2,
  GraduationCap,
  Brain
} from "lucide-react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { staggerContainer, fadeUpVariant, scaleUpVariant } from "@/lib/animations";
import { ScrollArea } from "@/components/ui/scroll-area";

const strategistSchema = z.object({
  syllabus: z.string().min(10, "Please enter the syllabus content."),
  timeframeNumber: z.string().min(1, "Please select a number."),
  timeframeUnit: z.enum(["days", "weeks", "months"]),
  learningPace: z.enum(["slow", "medium", "fast"]),
});

type StrategistFormValues = z.infer<typeof strategistSchema>;

export function StrategistForm() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<CreatePersonalizedStudyPlanOutput | null>(null);
  const [timeframeUnit, setTimeframeUnit] = useState<"days" | "weeks" | "months">("days");
  const { toast } = useToast();

  const form = useForm<StrategistFormValues>({
    resolver: zodResolver(strategistSchema),
    defaultValues: {
      syllabus: "",
      timeframeNumber: "7",
      timeframeUnit: "days",
      learningPace: "medium",
    },
  });

  async function onSubmit(values: StrategistFormValues) {
    setLoading(true);
    setResult(null);

    const timeframe = `${values.timeframeNumber} ${values.timeframeUnit}`;

    try {
      const plan = await createPersonalizedStudyPlan({
        syllabus: values.syllabus,
        timeframe: timeframe,
        learningPace: values.learningPace,
        pastExamPapers: "",
      });
      setResult(plan);
    } catch (e: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: e.message || "Failed to generate study plan. Please try again.",
      });
      console.error(e);
    } finally {
      setLoading(false);
    }
  }

  const handleUnitChange = (value: "days" | "weeks" | "months") => {
    setTimeframeUnit(value);
    form.setValue("timeframeUnit", value);
    // Reset number when unit changes
    const defaultNumber = value === "days" ? "7" : value === "weeks" ? "2" : "1";
    form.setValue("timeframeNumber", defaultNumber);
  };

  const handleSaveTimetable = () => {
    if (!result || !result.studyPlan || result.studyPlan.length === 0) {
      toast({
        variant: "destructive",
        title: "No timetable to save",
        description: "Please generate a study plan first.",
      });
      return;
    }

    try {
      // Create formatted text content
      const lines = [
        "═══════════════════════════════════════════════════════════════",
        "               YOUR PERSONALIZED STUDY PLAN",
        "                    Generated by UniPeasy",
        "═══════════════════════════════════════════════════════════════",
        "",
        `Generated on: ${new Date().toLocaleDateString('en-US', {
          weekday: 'long',
          year: 'numeric',
          month: 'long',
          day: 'numeric'
        })}`,
        "",
        "───────────────────────────────────────────────────────────────",
        "                           SCHEDULE",
        "───────────────────────────────────────────────────────────────",
        "",
      ];

      result.studyPlan.forEach((item, index) => {
        const priorityMarker = item.priority === 'High' ? '[HIGH]' : item.priority === 'Medium' ? '[MEDIUM]' : '[LOW]';
        lines.push(`DAY ${index + 1}: ${item.day}`);
        lines.push(`   Topic: ${item.topic}`);
        lines.push(`   Priority: ${priorityMarker}`);
        lines.push(`   Study Blocks: ${item.studyBlocks}`);
        lines.push(`   Duration: ${item.maxTimeToCover}`);
        lines.push("");
      });

      lines.push("───────────────────────────────────────────────────────────────");
      lines.push("                       STUDY TIPS");
      lines.push("───────────────────────────────────────────────────────────────");
      lines.push("");
      lines.push("  * Focus on high-priority topics first");
      lines.push("  * Take regular breaks (Pomodoro technique)");
      lines.push("  * Review completed topics periodically");
      lines.push("  * Stay consistent with your schedule");
      lines.push("");
      lines.push("═══════════════════════════════════════════════════════════════");
      lines.push("              Good luck with your studies!");
      lines.push("═══════════════════════════════════════════════════════════════");

      const content = lines.join("\n");

      // Create and download the file
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `study-plan-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "Study Plan Saved!",
        description: "Your personalized study plan has been downloaded successfully.",
      });
    } catch (error) {
      console.error("Error saving timetable:", error);
      toast({
        variant: "destructive",
        title: "Save Failed",
        description: "Failed to save timetable. Please try again.",
      });
    }
  };

  const getPriorityConfig = (priority: string) => {
    switch (priority) {
      case 'High':
        return {
          variant: 'destructive' as const,
          icon: <AlertTriangle className="w-3 h-3" />,
          className: 'bg-gradient-to-r from-red-500 to-rose-500 text-white border-0'
        };
      case 'Medium':
        return {
          variant: 'secondary' as const,
          icon: <Clock className="w-3 h-3" />,
          className: 'bg-gradient-to-r from-amber-500 to-orange-500 text-white border-0'
        };
      default:
        return {
          variant: 'secondary' as const,
          icon: <CheckCircle2 className="w-3 h-3" />,
          className: 'bg-gradient-to-r from-emerald-500 to-green-500 text-white border-0'
        };
    }
  };

  const showSaveButton = result && result.isFeasible && result.studyPlan && result.studyPlan.length > 0;

  return (
    <motion.div
      className="space-y-8"
      initial="hidden"
      animate="show"
      variants={staggerContainer}
    >
      {/* Hero Section */}
      <motion.div
        variants={fadeUpVariant}
        className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-primary/10 via-purple-500/10 to-pink-500/10 p-8 border border-primary/20"
      >
        <div className="absolute inset-0 bg-grid-white/5 [mask-image:linear-gradient(0deg,transparent,black)]" />
        <div className="absolute top-4 right-4 opacity-20">
          <Brain className="w-24 h-24 text-primary" />
        </div>
        <div className="relative z-10">
          <div className="flex items-center gap-3 mb-3">
            <div className="p-2 rounded-xl bg-primary/20 backdrop-blur-sm">
              <GraduationCap className="w-6 h-6 text-primary" />
            </div>
            <Badge variant="secondary" className="bg-primary/20 text-primary border-0">
              <Sparkles className="w-3 h-3 mr-1" />
              AI-Powered
            </Badge>
          </div>
          <h2 className="text-2xl font-bold bg-gradient-to-r from-primary via-purple-500 to-pink-500 bg-clip-text text-transparent mb-2">
            Exam Strategist
          </h2>
          <p className="text-muted-foreground max-w-xl">
            Let AI analyze your syllabus and create a personalized study schedule optimized for your learning pace and available time.
          </p>
        </div>
      </motion.div>

      <div className="grid lg:grid-cols-5 gap-6">
        {/* Input Form */}
        <motion.div variants={fadeUpVariant} className="lg:col-span-3">
          <Card className="border shadow-sm hover:shadow-lg transition-all duration-300 overflow-hidden group relative">
            <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-purple-500/5 opacity-0 group-hover:opacity-100 transition-opacity" />
            <CardContent className="p-6 relative">
              <div className="flex items-center gap-3 mb-6">
                <div className="p-2 rounded-lg bg-gradient-to-br from-primary/20 to-purple-500/20">
                  <BookOpen className="w-5 h-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-semibold">Study Configuration</h3>
                  <p className="text-xs text-muted-foreground">Fill in your exam details below</p>
                </div>
              </div>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5">
                  <FormField
                    control={form.control}
                    name="syllabus"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel className="flex items-center gap-2">
                          <Calendar className="w-4 h-4 text-primary" />
                          Syllabus Content
                        </FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="Paste the full syllabus here (e.g., Unit 1: Introduction, Unit 2: Advanced Topics...)"
                            className="h-40 resize-none border-muted-foreground/20 focus:border-primary/50 transition-colors"
                            {...field}
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <div className="grid md:grid-cols-2 gap-5">
                    <FormItem>
                      <FormLabel className="flex items-center gap-2">
                        <Clock className="w-4 h-4 text-primary" />
                        Timeframe
                      </FormLabel>
                      <div className="flex gap-2">
                        <FormField
                          control={form.control}
                          name="timeframeNumber"
                          render={({ field }) => (
                            <Select
                              onValueChange={field.onChange}
                              value={field.value}
                            >
                              <FormControl>
                                <SelectTrigger className="flex-1 border-muted-foreground/20 focus:border-primary/50">
                                  <SelectValue placeholder="Select" />
                                </SelectTrigger>
                              </FormControl>
                              <SelectContent>
                                {timeframeUnit === "days"
                                  ? Array.from({ length: 31 }, (_, i) => i + 1).map((num) => (
                                    <SelectItem key={num} value={String(num)}>
                                      {num}
                                    </SelectItem>
                                  ))
                                  : timeframeUnit === "weeks"
                                    ? Array.from({ length: 8 }, (_, i) => i + 1).map((num) => (
                                      <SelectItem key={num} value={String(num)}>
                                        {num}
                                      </SelectItem>
                                    ))
                                    : Array.from({ length: 12 }, (_, i) => i + 1).map((num) => (
                                      <SelectItem key={num} value={String(num)}>
                                        {num}
                                      </SelectItem>
                                    ))
                                }
                              </SelectContent>
                            </Select>
                          )}
                        />
                        <FormField
                          control={form.control}
                          name="timeframeUnit"
                          render={({ field }) => (
                            <Select
                              onValueChange={(value: "days" | "weeks" | "months") => handleUnitChange(value)}
                              value={field.value}
                            >
                              <FormControl>
                                <SelectTrigger className="w-28 border-muted-foreground/20 focus:border-primary/50">
                                  <SelectValue placeholder="Unit" />
                                </SelectTrigger>
                              </FormControl>
                              <SelectContent>
                                <SelectItem value="days">Days</SelectItem>
                                <SelectItem value="weeks">Weeks</SelectItem>
                                <SelectItem value="months">Months</SelectItem>
                              </SelectContent>
                            </Select>
                          )}
                        />
                      </div>
                      <FormMessage />
                    </FormItem>
                    <FormField
                      control={form.control}
                      name="learningPace"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="flex items-center gap-2">
                            <Rocket className="w-4 h-4 text-primary" />
                            Learning Pace
                          </FormLabel>
                          <Select
                            onValueChange={field.onChange}
                            defaultValue={field.value}
                          >
                            <FormControl>
                              <SelectTrigger className="border-muted-foreground/20 focus:border-primary/50">
                                <SelectValue placeholder="Select your pace" />
                              </SelectTrigger>
                            </FormControl>
                            <SelectContent>
                              <SelectItem value="slow">🐢 Slow & Steady</SelectItem>
                              <SelectItem value="medium">⚡ Average</SelectItem>
                              <SelectItem value="fast">🚀 Fast-paced</SelectItem>
                            </SelectContent>
                          </Select>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>

                  <motion.div
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                  >
                    <Button
                      type="submit"
                      disabled={loading}
                      className="w-full h-12 text-base font-medium bg-gradient-to-r from-primary via-purple-600 to-pink-600 hover:from-primary/90 hover:via-purple-600/90 hover:to-pink-600/90 shadow-lg shadow-primary/25"
                    >
                      {loading ? (
                        <>
                          <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                          Generating Your Plan...
                        </>
                      ) : (
                        <>
                          <Sparkles className="mr-2 h-5 w-5" />
                          Generate Study Plan
                        </>
                      )}
                    </Button>
                  </motion.div>
                </form>
              </Form>
            </CardContent>
          </Card>
        </motion.div>

        {/* Results Panel */}
        <motion.div variants={fadeUpVariant} className="lg:col-span-2">
          <Card className="border shadow-sm hover:shadow-lg transition-all duration-300 overflow-hidden">
            <CardContent className="p-6">
              <div className="flex items-center justify-between mb-5">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 rounded-lg bg-gradient-to-br from-primary/20 to-purple-500/20">
                    <Calendar className="w-4 h-4 text-primary" />
                  </div>
                  <div>
                    <h3 className="font-semibold">Your Timetable</h3>
                    {result && result.isFeasible && result.studyPlan && (
                      <p className="text-xs text-muted-foreground">{result.studyPlan.length} study sessions</p>
                    )}
                  </div>
                </div>

                {/* Save Button - Always visible when results exist */}
                {showSaveButton && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={handleSaveTimetable}
                    className="gap-2 border-primary/30 hover:bg-primary/10 hover:border-primary/50"
                  >
                    <Download className="w-4 h-4" />
                    Save
                  </Button>
                )}
              </div>

              {/* Loading State */}
              {loading && (
                <div className="flex flex-col items-center justify-center py-16">
                  <div className="relative">
                    <div className="absolute inset-0 bg-primary/20 rounded-full blur-xl animate-pulse" />
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                      className="relative"
                    >
                      <Brain className="h-12 w-12 text-primary" />
                    </motion.div>
                  </div>
                  <p className="mt-4 font-medium text-primary">Crafting your plan...</p>
                  <p className="text-sm text-muted-foreground mt-1">Analyzing syllabus & optimizing schedule</p>
                </div>
              )}

              {/* Results Display with ScrollArea */}
              {result && result.isFeasible && result.studyPlan && result.studyPlan.length > 0 && (
                <ScrollArea className="h-[450px] pr-3">
                  <motion.div
                    className="space-y-3"
                    initial="hidden"
                    animate="show"
                    variants={staggerContainer}
                  >
                    {result.studyPlan.map((item, index) => {
                      const priorityConfig = getPriorityConfig(item.priority);
                      return (
                        <motion.div
                          key={index}
                          variants={fadeUpVariant}
                          className="p-4 rounded-xl bg-gradient-to-br from-muted/50 to-muted/30 border border-muted-foreground/10 hover:border-primary/30 hover:shadow-md transition-all duration-300 group"
                        >
                          <div className="flex items-start justify-between gap-3">
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 mb-2">
                                <Badge variant="outline" className="text-xs font-normal bg-background/50">
                                  {item.day}
                                </Badge>
                                <Badge className={`text-xs gap-1 ${priorityConfig.className}`}>
                                  {priorityConfig.icon}
                                  {item.priority}
                                </Badge>
                              </div>
                              <p className="font-medium text-sm group-hover:text-primary transition-colors">{item.topic}</p>
                              <div className="flex items-center gap-3 mt-2 text-xs text-muted-foreground">
                                <span className="flex items-center gap-1">
                                  <Clock className="w-3 h-3" />
                                  {item.studyBlocks}
                                </span>
                                <span className="flex items-center gap-1">
                                  <Target className="w-3 h-3" />
                                  {item.maxTimeToCover}
                                </span>
                              </div>
                            </div>
                          </div>
                        </motion.div>
                      );
                    })}
                  </motion.div>
                </ScrollArea>
              )}

              {/* Infeasible Result */}
              {result && !result.isFeasible && (
                <motion.div variants={scaleUpVariant} initial="hidden" animate="show">
                  <Alert variant="destructive" className="border-destructive/50 bg-destructive/10">
                    <AlertTriangle className="h-4 w-4" />
                    <AlertTitle>Timeframe Too Short</AlertTitle>
                    <AlertDescription className="text-sm">
                      {result.message || "The timeframe is not realistic for this syllabus. Please provide more time or reduce the syllabus scope."}
                    </AlertDescription>
                  </Alert>
                </motion.div>
              )}

              {/* Empty State */}
              {!loading && !result && (
                <div className="text-center py-16 px-4">
                  <motion.div
                    className="relative w-20 h-20 mx-auto mb-4"
                    animate={{ y: [0, -8, 0] }}
                    transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
                  >
                    <div className="absolute inset-0 bg-gradient-to-br from-primary/30 to-purple-500/30 rounded-full blur-xl" />
                    <div className="relative w-full h-full rounded-full bg-gradient-to-br from-primary/20 to-purple-500/20 flex items-center justify-center border border-primary/20">
                      <Target className="w-8 h-8 text-primary" />
                    </div>
                  </motion.div>
                  <p className="font-semibold text-lg">Ready to plan?</p>
                  <p className="text-muted-foreground mt-1 text-sm max-w-xs mx-auto">
                    Fill out the form to generate your personalized AI-powered study schedule.
                  </p>
                </div>
              )}
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </motion.div>
  );
}
